### ISSUE TITLE
Using yarn in a DoneJS app requires --ignore-engines flag

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#761]
Any time I use yarn in a DoneJS app, I get the below error.  Here's the output from running `yarn add can-connect-feathers`

```
yarn add v0.17.10
warning my-app@0.0.1: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

As a workaround, you can get it to work by passing the `--ignore-engines` flag:

```
yarn add can-connect-feathers --ignore-engines
```

I think that the offending `hawk` package might be a sub-dependency of Steal, but I'm not sure, yet.

**Comment by matthewp** [comment]
You can do `npm ls hawk` to find out its heritage.

**Comment by imjoshdean** [comment]
While I am 100% in favor of getting this fixed, a temporary work-around would be to add a `.yarnrc` file with the following:

```
ignore-engines true
```

**Comment by frank-dspeed** [comment]
@marshallswain this is fixed in donejs 1.0 as documentjs is stripped out and gets replaced by bit-docs.
and no it was not a dependency of steal i think and when it was that update to latest steal solves that as @matthewp did always merged my pulls fast :+1: 

I fixed it manualy since monthes via simply having updated repos of the donejs packages i think all this is solved when the dependencys of all donejs products get updated via greenkeeper soon

**Comment by phillipskevin** [comment]
DocumentJS has not been replaced by bit-docs in DoneJS 1.0. We no longer install documentjs when you generate an app with `donejs add app`, but we still instruct users to install it with `donejs add documentjs`, so this is still an issue.

`hawk@0.10` is a sub-dependency of steal-tools@0.13 which documentjs uses.
